{% set name = "statistical-clear-sky" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  git_url: https://github.com/slacgismo/StatisticalClearSky

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy >=1.22
    - pandas
    - pip
    - python
    - seaborn
    - solar-data-tools
  run:
    - numpy >=1.22
    - pandas
    - python
    - seaborn
    - solar-data-tools

# test:
#   imports:
#     - statistical_clear_sky
#     - statistical_clear_sky.algorithm
#     - statistical_clear_sky.algorithm.initialization
#     - statistical_clear_sky.algorithm.serialization
#     - statistical_clear_sky.algorithm.plot
#     - statistical_clear_sky.algorithm.time_shift
#     - statistical_clear_sky.algorithm.utilities
#     - statistical_clear_sky.utilities
#   commands:
#     - python -m unittest

about:
  home: https://github.com/bmeyers/StatisticalClearSky
  license: BSD
  license_family: BSD
  license_file:
  summary: Statistical estimation of a clear sky signal from PV system power data
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - bmeyers
